#!groovy charset=UTF-8
pipeline {
  agent {
    kubernetes {
      label 'maven-agent'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.8.6-jdk-11
    command: ['cat']
    tty: true
    volumeMounts:
      - name: maven-cache
        mountPath: /root/.m2
  volumes:
    - name: maven-cache
      emptyDir: {}
'''
    }
  }
  
  options {
    skipStagesAfterUnstable()
  }
  
  stages {
    stage('Build') {
      steps {
        container('maven') {
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }
    
    stage('Test') {
      steps {
        container('maven') {
          sh 'mvn test'
        }
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }
    
    stage('Deliver') { 
      steps {
        // 确保这个脚本在容器内可用
        sh 'chmod +x jenkins/scripts/deliver.sh && ./jenkins/scripts/deliver.sh'
      }
    }
  }
}
